### ISSUE TITLE
MessagePropertiesInjectAdapter incompatible with pulsar-client 2.7.1, works with 2.10.4

### ISSUE THREAD

**Issue by sliwamichal** [streamnative/pulsar-tracing#22]
io.streamnative.pulsar.tracing.MessagePropertiesInjectAdapter 0.2.0 incompatible with org.apache.pulsar.client.impl.MessageImpl (2.7.1, works fine with 2.10.4)

org.apache.pulsar.client removed:
- msg.getMessageBuilder().addProperty() method
- org.apache.pulsar.common.api.proto.KeyValue class

{code}
08:44:57.191 [pulsar-client-io-1-1] WARN  o.a.p.c.impl.ConsumerInterceptors , - Error executing interceptor beforeConsume callback topic: persistent://tenant/namespace/topic-partition-0 consumerName: c0e18 java.lang.NoSuchMethodError: 'org.apache.pulsar.common.api.proto.MessageMetadata org.apache.pulsar.client.impl.MessageImpl.getMessageBuilder()' at io.streamnative.pulsar.tracing.MessagePropertiesInjectAdapter.put(MessagePropertiesInjectAdapter.java:49) at io.opentelemetry.opentracingshim.Propagation$TextMapSetter.set(Propagation.java:71) at io.opentelemetry.opentracingshim.Propagation$TextMapSetter.set(Propagation.java:64) at io.opentelemetry.api.trace.propagation.W3CTraceContextPropagator.inject(W3CTraceContextPropagator.java:123) at io.opentelemetry.context.propagation.MultiTextMapPropagator.inject(MultiTextMapPropagator.java:52)
{code}

![image](https://github.com/streamnative/pulsar-tracing/assets/104437934/f24bdc66-081e-42d7-ba30-1e14cf5fb8bc)
